### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats#1031]
There are certain questions that come up repeatedly on Gitter. I think we should create a FAQ for easy reference. Even if it doesn't prevent the questions from coming up, it should at least provide an easy explanation to link to instead of repeating a previous conversation.

Some common questions that come to mind:
- [x] What imports do I need for `<x>`? (see also #912)
- [x] Why am I still getting an error message about an implicit not being found even though I've imported `Future` instances? (see also #670)
- [x] How is cats different than scalaz? (#82 is somewhat relevant, but I think we also need to provide a little insight into cats' raison d'être)
- [x] How do I turn my list of `<x>` into an `<x>` of a list? (see also [this](https://twitter.com/tpolecat/status/721019769869045760) and [this](https://twitter.com/tpolecat/status/541111126155489280))
- [x] I'm new to FP. Any recommended resources for learning more?
  - @tpolecat has a [recommended reading list](http://tpolecat.github.io/2014/04/02/recommended-reading.html) on his site that has some good suggestions.
  - @jducoeur has recommended How to Bake Pi by Dr. Eugenia Cheng as an introduction to category theory.
- [x] I'm new to cats, but I'd like to contribute. How can I help?
- [x] Where is `Task`/`IO`? (#1227)
- [x] Where is `ListT`? (#1226)

**Comment by hamishdickson** [comment]
Would this be a good place to add something about the use of kind projector in the docs? Or would that be better placed in the docs themselves?

**Comment by ceedubs** [comment]
@hamishdickson I'm inclined to think that we should use type aliases instead of kind-projector in the docs wherever possible so we aren't throwing multiple things at people at once. If there are any docs that _do_ need to use kind-projector, then I think we should have a message in front of the first usage.

**Comment by hamishdickson** [comment]
👍 thats a much better idea

**Comment by ceedubs** [comment]
@hamishdickson I created #1033.

**Comment by yilinwei** [comment]
I think it would be awesome to have a glossary of operators for symbols such as `|@|` or `>>=`.

**Comment by ceedubs** [comment]
I'll work on this.

**Comment by OlivierBlanvillain** [comment]
The scala doc could be used a symbol index: http://typelevel.org/cats/api/#index.index-_

**Comment by jducoeur** [comment]
I should note that *How to Bake Pi* isn't an introduction to FP (or any kind of programming, really), it's an introduction to Category Theory in the math sense.  So it makes an excellent grounding in "what the heck are you all talking about?".  It's especially good for people who already know programming but *don't* know any category theory.  (Which is most programmers.)

**Comment by ceedubs** [comment]
@jducoeur good point. I'll add some clarification.

**Comment by kailuowang** [comment]
last item in the list merged. Closing the issue. Future additions to FAQ can be submitted through new issues.
