### ISSUE TITLE
Prepare for 0.9.0 release

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#1508]
It's been a little over two months since 0.8.0, and while there haven't been many big changes since then, I think it's probably time for a new release, and [at least three other people agree](https://gitter.im/typelevel/cats?at=58668696af6b364a29119a88). :smile:

There's nothing more in particular that I personally want to see in 0.9 besides #1506 (`flatMap` syntax for `Either` on 2.10 / 2.11 that's consistent with `Either#flatMap` in 2.12), but if other people have other things they'd like to wait for, we can expand this list:

- [x] Finish up #1506 (`flatMap` for `Either`, etc.) and get it reviewed and merged.
- [x] Merge #1466 (miscellaneous `StateT` stuff).
- [x] Merge #1475 (`Reducible` instances).
- [x] Merge #1509 (Scala.js update).
- [x] Merge #1500 (new operators for `Ior`).
- [x] Merge #1480 (`FunctionK#and`).
- [x] Merge #1455 (`NonEmptyList#reverse`).
- [x] Review #1510 (async `catchNonFatal` for `Future`).
- [x] One more review for #1452 (`Foldable#foldMapM`).
- [x] More eyes on #1505.
- [x] Review release notes and update before release (#1511).

~~I can write up the release notes on Monday (the 2nd), but if someone beats me to it I'd be happy to review instead.~~

**Comment by johnynek** [comment]
I want #1466 and #1475

**Comment by travisbrown** [comment]
@johnynek Added!

**Comment by notxcain** [comment]
I don't know if #1505 is fixable at all?

**Comment by johnynek** [comment]
I'd like to add #1500 too. If someone can give it one more +1.

**Comment by johnynek** [comment]
would like #1510 in too.

**Comment by johnynek** [comment]
I think #1480 is ready too.

By the way, I would mention we don't seem to be very proactive on reviewing and merging code. :/

**Comment by johnynek** [comment]
#1455 looks good too.

**Comment by johnynek** [comment]
#1452 also

**Comment by travisbrown** [comment]
@johnynek Updated again.

Maybe we should make it a matter of policy that if there's no obvious controversy in the PR the second maintainer to 👍 should be responsible for merging immediately? I know that personally if I review something with multiple 👍s that's been open for a while, I tend to assume that there's a reason it's not merged, and I don't merge it (which is of course self-perpetuating 😦).

**Comment by johnynek** [comment]
yeah, I'm +1 on that. revert is there if we want.

The bigger issues are the ones where there is 1 +1, but no other comments. Like no one else has looked and it should be simple in many cases.

**Comment by travisbrown** [comment]
The flip-side obligation for PR _openers_ will need to be that if there's been related conversation on Gitter it _must_ be linked in the PR. Again, I haven't personally been doing a good job of keeping up with Gitter recently, so if I see something with no comments I tend to assume I missed something there.

**Comment by travisbrown** [comment]
@notxcain I just took a look at #1505 and don't really have any idea how to help. I think we should spend some more time trying to fix it, but not before 0.9.0. Does that sound reasonable?

**Comment by philwills** [comment]
Is this still likely to get released soon? I've been planning to do a release of a downstream project, but have held off on the assumption that this was imminent.

**Comment by travisbrown** [comment]
@philwills Same here. I think we just need to get someone to merge #1511 and someone else with publishing rights to pull the trigger.

**Comment by adelbertc** [comment]
We should also be sure to update the README and website with the new version after.
