### ISSUE TITLE
Preparations for sbt 1.0.0

### ISSUE THREAD

**Issue by fthomas** [typelevel/cats#1848]
Over the last few days I started upgrading some sbt plugins as preparations for upgrading to sbt 1.0.0. This issue lists the plugins that need to be upgraded and tracks the progress of this effort:

- [x] partial-unification #1842 
- [x] sbt-coursier #1825 
- [x] sbt-doctest #1821 
- [x] sbt-ghpages #1852
- [x] sbt-git #1849 
- [x] sbt-jmh #1828 
- [x] sbt-microsites #1918 
- [x] sbt-mima-plugin #1824 
- [x] sbt-pgp #1860 
- [x] sbt-release #1829
- [x] sbt-scoverage #1861 
- [x] sbt-sonatype #1859 
- [x] sbt-unidoc #1843 
- [x] scalastyle-sbt-plugin #1839 

build.sbt changes:
- [x] curly braces for disabling tasks #1876 
- [x] add val for "compile-time" configuration #1889

**Comment by fthomas** [comment]
With @LukaJCB's help - thanks again, Luka - we have now updated all our sbt plugins to versions that are also available for sbt 1.0. So in principle we are now ready to update our build itself to sbt 1.0.

I'm unsure if I have time for that the next few days, so if someone else wants to do this, feel free!

**Comment by kailuowang** [comment]
thanks @fthomas and @LukaJCB , PR to update to sbt 1.0 just in. Had some weird issue with `Coursier`, so I just disable it temporarily.
