### ISSUE TITLE
Reenable full build on 2.13

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats#2347]
Right now several steps in build on 2.13-M4 were disabled temporarily to help release 2.13-M4 artifacts quickly 

- [ ]  code coverage disabled, due to lack of scoverage on 2.13-M4  [blocking issue](https://github.com/scoverage/scalac-scoverage-plugin/issues/225#issuecomment-405698919)
- [x] deprecation were ignored. need to find a way to cross-compile deprecated collection API, for now, it's just too much work that I don't have the time to do. https://github.com/typelevel/cats/issues/2893
- [ ] tut docs are disable also due to the deprecated collection APIs. 
- [ ] doctests are disabled, due to deprecated collection API and different toString implementations in collections. 
- [ ] scaladoc is disabled due to simulacrum stopped working on scaladoc compile on 2.13, possibly due to a scala macro bug reported to https://github.com/scala/bug/issues/11045

We should probably achieve these with multiple PRs.
If anyone is interested in picking one up, please announce it here.

**Comment by SethTisue** [comment]
should this stay open? is any of this still pending?

**Comment by kailuowang** [comment]
Only one of the 5 was resolved. I will take a look of them later.

**Comment by DieBauer** [comment]
Scaladoc and scoverage can be enabled. tut and doctest still have issues. Tut, as mentioned with the deprecation warnings and -Werror flag failing the build. 
doctest, for what I can see, unused imports in some snippets.

I'll create a PR for the first two.

**Comment by DieBauer** [comment]
I see two things, one is enable the 'full' build in sbt. e.g., all tasks can execute for both supported scala versions. The other is that the CI (travis) should be enabled for both versions. 

For travis I can see that cross-compiling scalaJs, and scalaFmt should be enabled. I can create a PR for that.
