### ISSUE TITLE
Backport 2.1.0 changes for Scala 2.11

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#3143]
As explained [here](https://www.reddit.com/r/scala/comments/dsf1xr/preparing_for_cats_210_help_wanted/) and in the [Cats 2019 roadmap](https://github.com/typelevel/cats/blob/master/ROADMAP_2019.md), we dropped support for Scala 2.11 on the Cats master branch after the 2.0.0 release, and we're relying on Scala 2.11 users to backport features from master to the `scala_2.11` branch for all future Cats releases.

We're planning to publish Cats 2.1.0-RC1 this Friday (15 November) and 2.1.0 by the end of this month. I've backported many of the build config changes and dependency updates to the 2.11 branch, but there are still many features that need to be backported in order for us to publish Cats 2.1.0 for Scala 2.11 (we're not necessarily aiming for 100% source compatibility between the 2.11 and 2.12 releases, but want to be close).

Note that many of the changes listed below are substantially more difficult to make on Scala 2.11 than on 2.12+ because adding methods to traits on 2.11 breaks binary compatibility (which is why we dropped decided to drop 2.11 support on master in the first place :smile:). You can see an example of what's necessary in [this pre-2.0 PR](https://github.com/typelevel/cats/pull/2609/files) adding an `ifA` method for `Apply`.

Pull requests currently merged on master that still need to be backported:

- [x]  Add `unzip` to `Functor`: #3062
- [ ]  Add `ifF` to `Functor`: #3040
- [x]  Add `Align`: #3076 
- [x]  Add `bifold` to `Bifoldable`: #3088
- [x]  Properly arrange `Parallel` instances: #3099
- [ ]  Fix `Vector` instances: #3100
- [x]  Add `attemptNarrow` to `ApplicativeErrorOps`: #2863
- [ ]  Add `TraverseFilter` instance for `Queue`: #3103
- [ ]  Fix `Eq` instances for tuples: #3105
- [x]  Add `minimumByOption`, etc.: #3084, #3122
- [x]  Add `sum` for `SemigroupK`: #3124
- [x]  Add `foldMapA`: #3135
- [x]  Add instances for `TailCalls.TailRec`: #3041
- [x]  Use `Foldable`'s `foldRight` for `Traverse`, etc.: #3015
- [x]  `CommutativeMonoid` for `Option` from `CommutativeSemigroup`: #2834
- [x]  Add `foldRightDefer` to `Foldable`: #2772
- [ ]  Fix constraint for `Hash` instances for `Map`: #3126
- [x]  Add `combineAllOption` to `Foldable`: #2380
- [ ] Fix `NonEmptyChain.fromSeq` signature: #3133 (in progress: #3134)
- [x] Add `separateFoldable`: #2742
- [x] Add `redeem` and `redeemWith`: #3146

Not yet merged but likely to be in 2.1.0-RC1:

- [ ] Move `adaptError`: #3148

I'll keep these checklists updated, and you can find a complete list of what will be included in 2.1.0-RC1 in the [milestone](https://github.com/typelevel/cats/milestone/11).

If most of these PRs aren't backported by the end of the month, it's unlikely that we'll publish Cats 2.1.0 for Scala 2.11. (We will continue to publish 2.0.x bugfix releases for Scala 2.11, and 2.1.0 will be backwards binary-compatible with 2.0, so even if we do drop 2.11 support in 2.1.0, that generally shouldn't cause major problems for Cats users who are still on Scala 2.11.)

Please comment here to let us know if you're working on backporting any of these changes, and please feel free to request reviews or other feedback from me or other Cats maintainers for backport PRs.

**Comment by gagandeepkalra** [comment]
@travisbrown is #3135 the correct Pull request for `Add foldMapA`, because I see another one there #3130, please confirm.

**Comment by gagandeepkalra** [comment]
Hello, I'm done with all of them, below is listed the status of those for which I didn't raise a PR.

Add ifF to Functor: #3040 => PR is already open #3131
Fix Vector instances: #3100 => This was reverted for broken BC
Fix Eq instances for tuples: #3105 => This was reverted for broken BC
Add foldMapA: #3135 => Need clarification, see comment [here](https://github.com/typelevel/cats/issues/3143#issuecomment-592800136)
Fix NonEmptyChain.fromSeq signature: #3133 => PR is already open #3134
Move adaptError: #3148 => Already available in 2.11

**Comment by larsrh** [comment]
I'm closing all 2.11-related tickets since there is not enough community interest in further releases.
