### ISSUE TITLE
typeclass-based collections implementations

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats#4147]
This is a recurring idea, most recently by @posco in https://github.com/typelevel/cats/pull/4118#issuecomment-1022714696.

> i.e. we should work towards having a typeclass based implementation of HashSet, SortedSet, HashMap, SortedMap that use only typeclasses, not the instance methods.

Although the issue comes up in Cats since this is where we house instances for Scala stdlib, this might be a better PR for cats-collections.

**Comment by djspiewak** [comment]
Definitely better for cats-collections. 🙂 This has been a dream for a while, but it's meaningfully hard to do correctly, and it's not clear to me that people would actually _use_ them over the standard library.

**Comment by armanbilge** [comment]
> it's meaningfully hard to do correctly

I thought somewhere someone suggested we could basically copy the implementations out of Scala itself. But I am very afraid of the collections hierarchy 😆 

> it's not clear to me that people would actually use them over the standard library.

yeah, fair ...

**Comment by rossabaker** [comment]
Precedent: `scalaz.Maybe` and `scalaz.IList` got used successfully where people didn't care about interop with stdlib, and were cursed mightily wherever people did.

**Comment by johnynek** [comment]
People definitely won't use what we don't have.

I have definitely sunk more time into code with zero users. I think it is worth it, even if it is niche. Someone could also learn a lot about HAMT by doing it, so it is a great learning experience.

One last note: cats-collections has two immutable heaps. The standard library has zero. No one generally uses them, but I have and I bet a few others. Safe immutable types are a big part of our mission. Let's not give into "no one will use this" defeatism. They may not, but that is not how we measure success.

**Comment by armanbilge** [comment]
A comment by @durban in https://github.com/typelevel/cats-effect/pull/2464 reminded me of this issue:
> What I find very strange is that it uses universal equality/hash for the keys, while there is a `Hash` typeclass in Cats.
- https://github.com/typelevel/cats-effect/pull/2464#issuecomment-991976013

Understandably, it is difficult to provide even a `Ref`-based `MapRef` implementation using `Hash` when we are lacking a `Map` based on `Hash`!

So even if `Map` is something "nobody" would use, `MapRef` certainly is.

**Comment by johnynek** [comment]
well, if you don't worry to much about performance, here is how:

```scala
class Hashed[K](implicit hash: Hash[K]) {

  class Key(val unwrap: K) {
    override val hashCode: Int = hash.hashOf(unwrap)
      that match {
        case hk: HashKey => hash.eqv(unwrap, hk.unwrap)
        case _ => false 
     }
  }

  def toMap[V](kvs: Iterable[K, V]): Map[Key, V] =
    kvs.iterator.map { case (k, v) => (new Key(k), v) }.toMap
}

val keySpace = new Hashed[Foo]

val myMap: Map[keySpace.Key, String] = keySpace.toMap(List(Foo(1) -> "1"))
```

etc....

so, in other words, you box with something that delegates hashCode and equals to Hash.

**Comment by johnynek** [comment]
I mean, we could add these methods and inner types to `Hash[K]` now... and have `toMap` and `toSet` and it might be pretty usable.

**Comment by DavidGregory084** [comment]
I think I am going to have a crack at this one unless someone has already taken it?

My plan is to do a pretty conservative port of the HashMap and HashSet from the Scala 2.13 collections initially.

e.g. for HashSet. something like this:
```scala
abstract class HashSet[A] {
  final def contains(value: A)(implicit hash: Hash[A]): Boolean

  final def get(value: A)(implicit hash: Hash[A]): Option[A]

  final def add(value: A)(implicit hash: Hash[A]): HashSet[A] 

  final def remove(value: A)(implicit hash: Hash[A]): HashSet[A] 
}
```

Essentially, the interface of the existing Scala collections but with the Hash constraint . :)

I have not really looked into any kind of caching of hash code values or the many optimizations that have been added to the 2.13.x collections since the initial CHAMP port as I think it's probably best to do the simplest possible implementation to begin with.

**Comment by djspiewak** [comment]
In general, passing it to each method is superior because it allows call sites to more correctly reflect their constraints. For example, imagine the constructor of `MapRef[F, K, V]`. You shouldn't need a `Hash[K]` to *construct* a `MapRef`, only to write key/value pairs. This makes the type signatures of both the functions using the constructor and the functions using the accessors much more parametric in terms of the constraints they declare, which in turn makes it easier to infer their semantics.

**Comment by armanbilge** [comment]
Ah, ok, thanks both. That makes sense, and I see that cats-collections also uses method-level constraints. 👍

**Comment by durban** [comment]
On the other hand, if `MapRef` looks like this:
```scala
trait MapRef[F[_], K, V] {
  def lookup(k: K)(implicit K: Hash[K]): Ref[F, V]
}
```
then we may also need `OrderMapRef` (which may store them in a tree):
```scala
trait OrderMapRef[F[_], K, V] {
  def lookup(k: K)(implicit K: Order[K]): Ref[F, V]
}
```

If the 2 constructors receive the `Hash`/`Order` instead, then a single `MapRef` trait can be used by both.

**Comment by satorg** [comment]
I have a quite crazy idea on how we could approach that. What if we consider generalizing it:
```scala
trait GenMap[C[_], K, V] {
  def get(k: K)(implicit C: C[K]): Option[V]
  def updated(k: K, v: V)(implicit C: C[K]): GenMap[C, K, V]

  def toMap(implicit C: C[K]): Map[K, V] // latches the constraint `C` inside a regular `Map` interface implementation
                                         // can be implemented efficiently as a view of the original `GenMap`
                                         // thus avoiding copying of any data
  
  def toGenMap[CC[_]]: GenMap[CC, K, V] // changes the constraint type
                                        // also should be possible to avoid copying of data
}

type HashMap[K, V] = GenMap[Hash, K, V]
type OrderMap[K, V] = GenMap[Order, K, V]
```

**Comment by johnynek** [comment]
how can you convert between `HashMap[K, V]` and `OrderMap[K, V]` without any copying?

Not only does the internal structure depend on the kind of map it is (sorted or hash) it depends on the *value* of the sorting and hashing (of which there can be many due to no coherent typeclasses in scala).

I continue to think this approach (each callsite takes the dependency) is actually a haskell cargo-cult and not a great design in scala.

The internal structure only makes sense when you use the right value for the typeclass. By not keeping it together you are just hoping that users don't pass the wrong ones.

I think binding the typeclass instance to the value like scala does with `SortedMap` and `SortedSet` is actually the right way to go even though it isn't how haskell works (in part because haskell does not capture typeclasses reified into values very often, although it is possible).

**Comment by satorg** [comment]
Oh no, disregard please. It won't work, I didn't think through enough)

**Comment by satorg** [comment]
> The internal structure only makes sense when you use the right value for the typeclass. By not keeping it together you are just hoping that users don't pass the wrong ones.

Yes, I agree it is a good point. It is just safer to bind internal structure and a constraint together.

In fact, we cannot even construct a new instance (besides an empty one) without passing the constraint to the constructor.

**Comment by DavidGregory084** [comment]
I've pushed a WIP PR for the HashSet implementation under #4185, interested in all of your thoughts about it!

I'd like to write more tests and add some benchmarks for what is there now, but we also need to decide on a few things:

* Does this belong in cats at all or in cats-collections? I have no opinion about this other than I'm not aware that cats-collections has many users.
* What is the minimal set of operations that we should support? There are a bunch of things (subSetOf, diff, filter) that I haven't currently implemented.
* Should the Hash constraint appear at the method level or at the constructor level in HashSet?

**Comment by armanbilge** [comment]
Btw, we also have to do something about this law:

https://github.com/typelevel/cats/blob/fe40bc2b4961386d829c0dd594af9bd80941947d/kernel-laws/shared/src/main/scala/cats/kernel/laws/HashLaws.scala#L33-L35

See discussion in https://github.com/typelevel/cats/pull/4118#issuecomment-1023473730.

**Comment by DavidGregory084** [comment]
I've pushed #4193 containing a hash map implementation along the same lines.

Some things I still need to do:
- [ ] address #4189 in both PRs
- [ ] add benchmarks for #4193
- [ ] re-run benchmarks for #4185 as I just fixed a bug in `remove` (unfortunately this takes ~30hrs)

**Comment by johnynek** [comment]
should we close this since it was ultimately rejected and pushed to cats-collections?

**Comment by johnynek** [comment]
Also note since this was opened

https://github.com/typelevel/cats/blob/83ad02b525946c7eb6f74205f6c1968a08a6e75b/core/src/main/scala/cats/TraverseFilter.scala#L127

`hashDistinct` was merged. That conflates `Hash[A]` with `a.hashCode` which is not true for many interesting `opaque type` values that we might want to use. We could solve this example by making a wrapper that delegates to `Hash` for equality and hashing at the cost of an extra allocation. Given that we are using `State` I don't think that will be a hit on perf.

**Comment by DavidGregory084** [comment]
The HashMap / HashSet portion of this has been contributed to cats-collections now - see https://github.com/typelevel/cats-collections/pull/534 and https://github.com/typelevel/cats-collections/pull/533. I am not sure if I will have an opportunity to work on a `SortedSet` or `SortedMap` soon so I think this should stay open but I have unassigned myself for the moment.

**Comment by DavidGregory084** [comment]
Yes that's a good point - I suppose the problem is that the `hashCode` calculation cannot be overridden to use a `cats.kernel.Hash`.

**Comment by armanbilge** [comment]
Eh, I wouldn't really consider that a problem. If you use the cats `Hash` instance (instead of the universal `hashCode` method) it will do the right thing.
