### ISSUE TITLE
Let's talk the next release (0.4.0 edition)

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#834]
Previously: #486, #594. It's been almost three months since 0.3.0 and there are potentially some big changes coming in #786, so we think it's time for an 0.4.0 release.

Update on progress from [Gitter](https://gitter.im/non/cats?at=56acfbc480ad69394a7b6868) this morning:

> #781: Done.
> #772: Done.
> #757: Seems close to ready after #772, with one open question (about whether the compose should be there).
> #821 [now #833]: We've got a fix—we just need a name for the ap on CartesianBuilderN and a Simulacrum 0.6.2 release—so I think it should go in.
> #723: I'd still really like to see 0.4.0 published to the `org.typelevel` group, and there seems to be agreement that that's a good idea, so I guess it's up to @non to decide whether he wants to deal with the changes to the release process now or later.
> #817: I could go either way—I like the current proposal but don't think it has to make it into 0.4.0.
> #631: I changed my mind here because of Algebra-related complications that might be changing / going away soon, and I don't think it belongs in this release.

Here's what still needs to happen:

- [x] Get #833 (the follow-up to #821) reviewed and merged.
- [x] Make a decision on `compose` in #757 and get it reviewed and merged.
- [x] Implement `Monoidal` as proposed in #817 (paging @julienrf).
- [x] Decide on publishing to `org.typelevel` (see #723; paging @non).
- [x] Write up release notes (I'm working on this).

Please comment here as soon as possible if there's other stuff you really want to see in 0.4.0.

**Comment by non** [comment]
I'm fine with publishing to `org.typelevel`. I also want to move this repo to typelevel. We already got consensus on both points.

Is there any reason for me not to just do that today?

**Comment by travisbrown** [comment]
@non Sounds good to me!—I just know nothing about who has the ability to publish to `org.typelevel`, etc., so I wasn't sure how much of a hassle it would be.

**Comment by longcao** [comment]
Where does the { `non` | `org.typelevel` }.github.io/cats documentation fit into the release (or the release process in general)? AFAIK the [current site](http://non.github.io/cats/) doesn't appear to have been pushed in awhile, as it says "Last updated on September 19, 2015".

**Comment by non** [comment]
@longcao Well -- if we move the repo to typelevel then yeah, we'll have to update a lot of links (internal and external). I wonder if it would be worth just using a domain name rather than exposing the repo information in the URL?

**Comment by longcao** [comment]
@non ah yeah I hadn't even thought of that, I was thinking about whether the doc pages are pushed in parallel with publishing a new release

**Comment by clhodapp** [comment]
Were you planning on waiting for shapeless 2.3 for this release? If so, it'd be nice if the stuff I did in https://github.com/milessabin/shapeless/pull/524 could be leveraged in circe's derived codecs.

**Comment by fthomas** [comment]
@clhodapp I don't understand why Cats should wait for shapeless. We don't have a direct dependency on shapeless. What am I missing?

**Comment by ceedubs** [comment]
Regarding #757: since Miles is on holiday, I've opened up #843 as a replacement. It includes the changes from #757 along with resolving merge conflicts and incorporating the discussed changes.

**Comment by ceedubs** [comment]
After [this comment](https://github.com/typelevel/cats/issues/817#issuecomment-177851454), it sounds like we are going to wait on `Monoidal`, and that release notes are probably the only pending item!

**Comment by travisbrown** [comment]
@ceedubs Great! I'm finishing them up right now. Last time we published the final version of the release notes after the release, so if someone who has access wants to get the release process started now, it sounds like we could consider ourselves ready.

**Comment by non** [comment]
Do we want to release now? Or wait for #817?

**Comment by travisbrown** [comment]
@non My vote is not wait.

**Comment by ceedubs** [comment]
@non agreed. Let's go ahead and release.

**Comment by travisbrown** [comment]
Okay, we're not waiting on #817, and I've just posted release notes for review in #848, so all the boxes are checked.

**Comment by travisbrown** [comment]
Resolved by afa0ed2a03c826d799bb940ec5deeb1888c23438.
