### ISSUE TITLE
Let's talk the next release (0.5.0)

### ISSUE THREAD

**Issue by travisbrown** [typelevel/cats#966]
Previously: #486, #594, #834. I think we were planning to get the cats-kernel rearrangement into 0.5.0, but it's been two months since 0.4.0, a lot has happened since then, we have at least [one person with a good reason](https://gitter.im/typelevel/cats?at=5701a92576b6f9de194dbfe2) to want a new stable version, and I'm planning to release circe 0.4.0 in the next day or two, so I think it's worth considering cutting a 0.5.0 release now.

(For what it's worth, none of my projects with Cats dependencies require any changes to update from 0.4.1 to the current 0.5.0-SNAPSHOT.)

I'd be happy just to set the cutoff as whatever makes it to master before I've got the release notes written, but we could also wait if there's anything anyone particularly wants to have included.

---

Okay, checklist time:

- [x] Review `MonadWriter`: #911
- [x] Provide a default implementation for `ap` (or `product`): #904 
- [ ] Consider adding `Compose` and `Bicompose`: #900 
- [ ] Refactor `MonadFilter` and `MonadCombine` so that instances can be provided for e.g. `XorT`: #694, #695 
- [x] Publish a new Algebra release and depend on it here: #994

**Comment by adelbertc** [comment]
Things of interest to me:

* Define `map` and `product` in terms of `ap` (or vice versa) for `Applicative` until we have a solid proposal for breaking out default implementations (https://github.com/typelevel/cats/issues/904)
* MonadWriter https://github.com/typelevel/cats/pull/911
* Compose data type https://github.com/typelevel/cats/issues/900

**Comment by adelbertc** [comment]
Oh one thing that I think a lot of folks may want is a new Algebra release. We've been asked about the tuple stuff for `Monoid` and co. a couple times now which is in master but hasn't been released yet.

**Comment by ShaneDelmore** [comment]
I would love to see https://github.com/typelevel/cats/issues/695 in 0.5.0.  My team has been working around it just fine but it is causing new contributors to our code some confusion as they don't understand why "if" doesn't work in for comprehensions as they would expect.

**Comment by travisbrown** [comment]
I agree that all these things are valuable but I'm quickly becoming less convinced that I want the circe 0.4.0 release to wait for Cats 0.5.0.

**Comment by kailuowang** [comment]
I agree with these valuable things, but to make all the other already implemented features during the last 2 mo, shall we consider a 0.5.0 release now and a 0.6.0 later? Or just a 0.5.0-M1 release would help.

**Comment by non** [comment]
Should we just release what we have as 0.5.0?

**Comment by travisbrown** [comment]
@non That sounds reasonable to me.

**Comment by adelbertc** [comment]
I'd at least like:

Review MonadWriter: #911 (just needs one more +1)

and 

Publish a new Algebra release and depend on it here. (people have been asking for tuple instances for a while)

**Comment by ceedubs** [comment]
I just updated the checkboxes. We opted to not wait for a couple of the items, but this release has happened, so I'm going to close out this issue.
